### ISSUE TITLE
Add RGB leds to the board

### ISSUE THREAD

**Issue by tulku** [dreamster/dreamster-board#3]
We wanted to have some LEDs to allow easily debugging.

We thought of having LEDs in parallel to save pins but still have enough lights to make it nice.

**Comment by yagui** [comment]
any suggestion? I don't know any popular RGB led

**Comment by tulku** [comment]
@sebascerone can we re use the LED that we use in LESS boards? Which one is it?

**Comment by sebascerone** [comment]
I don't think so, digikey just send me an email tell me it is deprecated.
Why don'y we use just SMD LED?

Regards,
Sebastian

2015-02-07 14:48 GMT-03:00 tulku notifications@github.com:

**Comment by tulku** [comment]
I don't understand... I guess that Ariel wants the specific LED so that he
can check currents, and connections... And not just if it is SMD or DIP...

"Oh no, not again."
- A bowl of petunias on its way to certain death.
