### ISSUE TITLE
Add sound to dreamster

### ISSUE THREAD

**Issue by tulku** [dreamster/dreamster-board#4]
Having sound could be nice. In the current dream-sheild version, can we easily add something to reproduce sounds (like human voice, recorded mp3s)?

Please take into account that we can just hack one or two robots and not add sound to all the robots.

**Comment by tulku** [comment]
To add audio, we could put an stereo audio codec and an SD reader. We don't need to decode MP3, that circuito wouldn't be so complex nor expensive.

Something like this could be use to read the SD:
https://learn.adafruit.com/adafruit-micro-sd-breakout-board-card-tutorial

And something like this to use as Stereo Audio CODEC:
http://ar.mouser.com/Search/Refine.aspx?Keyword=WM8731

There is a board from which we can copy schematics and library:
https://www.sparkfun.com/products/11290
![screenshot from 2015-02-06 22 02 16](https://cloud.githubusercontent.com/assets/764126/6090029/f919685e-ae4b-11e4-94cb-fb1f0864d11e.png)

The board seems to be based in this project: http://wiki.openmusiclabs.com/wiki/AudioCodecShield

**Comment by tulku** [comment]
It seems, according to @ernestmc that the output power of this IC will not drive a speaker. We should add some aplification stage to make it louder.

**Comment by yagui** [comment]
I dont understand what is the goal. 

We want to add sound to some boars but not all? 
It should be in the dreamster shield schematics and we solder it just in a few? or is an extra board that we could add in some prototypes?

We want microphone AND recorded sound? or is one or the other.

If we gonna put an SD, I wouldn't use a codec. I'd just save raw sound, and simplify the circuit.

**Comment by tulku** [comment]
If we can make it simple and cheap enough it would be nice to put it on every board, if not just a few.

I think that having the footprints in the board and use them or not is better than having an add on board.

I like your idea... Just store the samples in the SD, output PWM, filter and then use a simple amplifier?

Could you add that to the schematics?

**Comment by yagui** [comment]
if we use a SD card we need 4 pins for spi. Do we have other options?

**Comment by tulku** [comment]
I don't think so. We do not have those pins?

"Oh no, not again."
- A bowl of petunias on its way to certain death.

**Comment by yagui** [comment]
we are one pin short.
maybe we can leave the ir sensor's leds always on.

**Comment by tulku** [comment]
@Martin-MT thought that this was a bad idea, but I don't remember why.

**Comment by yagui** [comment]
ok, we can share a pin. The leds enable of ir sensors and mosi (cmd) line of the sd. When using the ir sensors the ChipSelect line of the sd should be disabled. When using the SD, the led of ir sensor will flash randomly. If we do not make readings of the sensors while using the SD, I think it will be ok. What do you think?

**Comment by ernestmc** [comment]
Just one word: BUS. Make the IR sensors and all other sensors work independently with a small dedicated uP that manages the polling on pogrammable intervals or otherwise. Another benefit of this approach is that you can make them separate plugable modules.

**Comment by yagui** [comment]
It's getting complicated. I think this first version should be simple. What if we forget about the SD card and generate simple sounds like tones?

**Comment by tulku** [comment]
Ok. I like the idea of sharing the Pin. We will not have an sd reader per
robot, so we will be generating tones for most of them. In the ones that we
want to have proper sounds, we can share the pin.

Lucas

"Oh no, not again."
- A bowl of petunias on its way to certain death.
