### ISSUE TITLE
Do we want to use the L9110 h bridge?

### ISSUE THREAD

**Issue by tulku** [dreamster/dreamster-board#5]
The H-bridge present in the most common "arduino driver for motors" is the L9110. That IC is no were to be found, execpt in Alibaba, where it is incredible cheap:

http://www.alibaba.com/product-detail/L9110-L9110S_60135131276.html

@yagui, @sebascerone Will we be able to source the components? Shall we use a more trusty part? Switch to a TI h bridge?

**Comment by sebascerone** [comment]
> @yagui https://github.com/yagui, @sebascerone
> https://github.com/sebascerone Will we be able to source the
> components? Shall we use a more trusty part? Switch to a TI h bridge?
> 
> We should use LMD18200 from TI. It is the same I used for TCO.

Regards,
Sebastian

**Comment by yagui** [comment]
DRV8833C looks about similar to L9110 and is one of the least expensive in ti webpage
http://www.ti.com/product/DRV8833C
$2.24 or $0.8 | 1ku

LMD18200 has more output current, it says 12V operation, and is more expensive
$17.01 or $8.10 | 1ku
www.ti.com/product/LMD18200
If we want more current rate there other options in ti web 
http://www.ti.com/product/drv8848
is a good option or
http://www.ti.com/product/drv8841
another one

**Comment by sebascerone** [comment]
Forget LMD 18200, it is a lot of money!!!

2015-02-07 10:33 GMT-03:00 Ariel Burman notifications@github.com:

**Comment by tulku** [comment]
@sebascerone  what do you thing, DRV8833C or L9110? The TI one seems cheap enough and I would think that it's more reliable.

**Comment by sebascerone** [comment]
I always prefer texas than a chinese IC.

2015-02-07 14:52 GMT-03:00 tulku notifications@github.com:

**Comment by tulku** [comment]
Ok, then we switch to the DRV8833C.
